version: '3'
services:
  pg:
    image: 'postgres:11.10'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
#    volumes:
#      - postgres:/var/lib/postgresql/data
#volumes:
