branch-defaults:
  master:
    environment: Awsvodbe-env-1
environment-defaults:
  Awsvodbe-env-1:
    branch: null
    repository: null
global:
  application_name: aws_VOD_BE
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: ./myapp.zip
